### ISSUE TITLE
check_workshop.ipynb is not running fine under the current environment

### ISSUE THREAD

**Issue by weikang9009** [sjsrey/pysalfoss4g19#2]
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-af984a94685c> in <module>
----> 1 import mplleaflet as mpll

ModuleNotFoundError: No module named 'mplleaflet'
ModuleNotFoundError: No module named 'mplleaflet'
```

**Comment by knaaptime** [comment]
I kept getting this earlier today because Jupyter and mplleaflet were installed in different environments. I had to install mplleaflet in my base environment in addition to the workshop env

**Comment by weikang9009** [comment]
I think we should delete the check on `mplleaflet` in check_workshop.ipynb since it is not included in the recipe for building the conda env. There are several other checks we need to drop (like `libpysal`...). Serge might forget to update the notebook when changing the conda env.

**Comment by sjsrey** [comment]
fixed - thanks for spotting.
